### ISSUE TITLE
Issue in the post/users/create user endpoint 

### ISSUE THREAD

**Issue by sso927** [sso927/event_manager#3]
There are null links/url in the output for the create user endpoint when the input includes them. These links must be added.

**Comment by jjyutm4532** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the UserService.create method to include profile_picture_url, linkedin_profile_url, and github_profile_url in the new user creation process. This ensures that these URLs are saved when provided in the input.

You can review changes in this commit: https://github.com/jjyutm4532/sso927-event_manager-3/commit/a189ec5daa9564d2f078be2417cbcd94331b9219.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
